# Generated by Django 3.0.6 on 2020-06-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20200626_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.SessionYearModel'),
        ),
    ]
